<?php
/**
 * MePbx
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v0
 *
 * OpenAPI spec version: 2016-05-13T11:31:53Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * MePbx Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MePbx implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Me_pbx';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'system_status' => 'string',
        'state' => 'string',
        'instance_status' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'system_status' => 'systemStatus',
        'state' => 'state',
        'instance_status' => 'instanceStatus'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'system_status' => 'setSystemStatus',
        'state' => 'setState',
        'instance_status' => 'setInstanceStatus'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'system_status' => 'getSystemStatus',
        'state' => 'getState',
        'instance_status' => 'getInstanceStatus'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const SYSTEM_STATUS_GREEN = 'green';
    const SYSTEM_STATUS_FAILED = 'failed';
    const SYSTEM_STATUS_RED = 'red';
    const STATE_GREEN = 'green';
    const STATE_FAILED = 'failed';
    const STATE_RED = 'red';
    const INSTANCE_STATUS_GREEN = 'green';
    const INSTANCE_STATUS_FAILED = 'failed';
    const INSTANCE_STATUS_RED = 'red';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getSystemStatusAllowableValues()
    {
        return [
            self::SYSTEM_STATUS_GREEN,
            self::SYSTEM_STATUS_FAILED,
            self::SYSTEM_STATUS_RED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_GREEN,
            self::STATE_FAILED,
            self::STATE_RED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getInstanceStatusAllowableValues()
    {
        return [
            self::INSTANCE_STATUS_GREEN,
            self::INSTANCE_STATUS_FAILED,
            self::INSTANCE_STATUS_RED,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['system_status'] = isset($data['system_status']) ? $data['system_status'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['instance_status'] = isset($data['instance_status']) ? $data['instance_status'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("green", "failed", "red");
        if (!in_array($this->container['system_status'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'system_status', must be one of #{allowed_values}.";
        }
        $allowed_values = array("green", "failed", "red");
        if (!in_array($this->container['state'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'state', must be one of #{allowed_values}.";
        }
        $allowed_values = array("green", "failed", "red");
        if (!in_array($this->container['instance_status'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'instance_status', must be one of #{allowed_values}.";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("green", "failed", "red");
        if (!in_array($this->container['system_status'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("green", "failed", "red");
        if (!in_array($this->container['state'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("green", "failed", "red");
        if (!in_array($this->container['instance_status'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets system_status
     * @return string
     */
    public function getSystemStatus()
    {
        return $this->container['system_status'];
    }

    /**
     * Sets system_status
     * @param string $system_status
     * @return $this
     */
    public function setSystemStatus($system_status)
    {
        $allowed_values = array('green', 'failed', 'red');
        if (!in_array($system_status, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'system_status', must be one of 'green', 'failed', 'red'");
        }
        $this->container['system_status'] = $system_status;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state
     * @return $this
     */
    public function setState($state)
    {
        $allowed_values = array('green', 'failed', 'red');
        if (!in_array($state, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'state', must be one of 'green', 'failed', 'red'");
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets instance_status
     * @return string
     */
    public function getInstanceStatus()
    {
        return $this->container['instance_status'];
    }

    /**
     * Sets instance_status
     * @param string $instance_status
     * @return $this
     */
    public function setInstanceStatus($instance_status)
    {
        $allowed_values = array('green', 'failed', 'red');
        if (!in_array($instance_status, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'instance_status', must be one of 'green', 'failed', 'red'");
        }
        $this->container['instance_status'] = $instance_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
