<?php
/**
 * QueuesResponseQueues
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
<<<<<<< HEAD
 * @author   Swaagger Codegen team
=======
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v0
 *
<<<<<<< HEAD
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-03-27T11:07:47Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
=======
 * OpenAPI spec version: 2016-05-13T11:31:53Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * QueuesResponseQueues Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
<<<<<<< HEAD
 * @author      Swagger Codegen team
=======
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QueuesResponseQueues implements ArrayAccess
{
<<<<<<< HEAD
    const DISCRIMINATOR = null;

=======
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'QueuesResponse_queues';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
<<<<<<< HEAD
    protected static $swaggerTypes = [
        'name' => 'string',
        'id' => 'int',
        'number' => 'int'
    ];
=======
    protected static $swaggerTypes = array(
        'number' => 'int',
        'name' => 'string',
        'id' => 'int'
    );
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
<<<<<<< HEAD
    protected static $attributeMap = [
        'name' => 'name',
        'id' => 'id',
        'number' => 'number'
    ];

=======
    protected static $attributeMap = array(
        'number' => 'number',
        'name' => 'name',
        'id' => 'id'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
<<<<<<< HEAD
    protected static $setters = [
        'name' => 'setName',
        'id' => 'setId',
        'number' => 'setNumber'
    ];

=======
    protected static $setters = array(
        'number' => 'setNumber',
        'name' => 'setName',
        'id' => 'setId'
    );

    public static function setters()
    {
        return self::$setters;
    }
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
<<<<<<< HEAD
    protected static $getters = [
        'name' => 'getName',
        'id' => 'getId',
        'number' => 'getNumber'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }
=======
    protected static $getters = array(
        'number' => 'getNumber',
        'name' => 'getName',
        'id' => 'getId'
    );
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
<<<<<<< HEAD
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
=======
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
<<<<<<< HEAD
        $invalid_properties = [];

        if (!is_null($this->container['id']) && ($this->container['id'] <= 0)) {
            $invalid_properties[] = "invalid value for 'id', must be bigger than 0.";
        }

        if (!is_null($this->container['number']) && ($this->container['number'] <= 0)) {
            $invalid_properties[] = "invalid value for 'number', must be bigger than 0.";
        }

=======
        $invalid_properties = array();
        if ($this->container['number'] < 0.0) {
            $invalid_properties[] = "invalid value for 'number', must be bigger than or equal to 0.0.";
        }
        if ($this->container['id'] < 0.0) {
            $invalid_properties[] = "invalid value for 'id', must be bigger than or equal to 0.0.";
        }
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
<<<<<<< HEAD
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['id'] <= 0) {
            return false;
        }
        if ($this->container['number'] <= 0) {
=======
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['number'] < 0.0) {
            return false;
        }
        if ($this->container['id'] < 0.0) {
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
            return false;
        }
        return true;
    }


    /**
<<<<<<< HEAD
=======
     * Gets number
     * @return int
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     * @param int $number
     * @return $this
     */
    public function setNumber($number)
    {

        if ($number < 0.0) {
            throw new \InvalidArgumentException('invalid value for $number when calling QueuesResponseQueues., must be bigger than or equal to 0.0.');
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {

<<<<<<< HEAD
        if (!is_null($id) && ($id <= 0)) {
            throw new \InvalidArgumentException('invalid value for $id when calling QueuesResponseQueues., must be bigger than 0.');
        }

=======
        if ($id < 0.0) {
            throw new \InvalidArgumentException('invalid value for $id when calling QueuesResponseQueues., must be bigger than or equal to 0.0.');
        }
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
        $this->container['id'] = $id;

        return $this;
    }
<<<<<<< HEAD

    /**
     * Gets number
     * @return int
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     * @param int $number
     * @return $this
     */
    public function setNumber($number)
    {

        if (!is_null($number) && ($number <= 0)) {
            throw new \InvalidArgumentException('invalid value for $number when calling QueuesResponseQueues., must be bigger than 0.');
        }

        $this->container['number'] = $number;

        return $this;
    }
=======
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
<<<<<<< HEAD


=======
>>>>>>> c2576243bd211077fbb5e257621d2949c63caa05
