<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v0
 *
 * OpenAPI spec version: 2016-05-13T11:31:53Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for aclDelete
     *
     * .
     *
     */
    public function testAclDelete()
    {

    }
    /**
     * Test case for aclGet
     *
     * .
     *
     */
    public function testAclGet()
    {

    }
    /**
     * Test case for aclOptions
     *
     * .
     *
     */
    public function testAclOptions()
    {

    }
    /**
     * Test case for aclPatch
     *
     * .
     *
     */
    public function testAclPatch()
    {

    }
    /**
     * Test case for blacklistIdDelete
     *
     * .
     *
     */
    public function testBlacklistIdDelete()
    {

    }
    /**
     * Test case for blacklistIdOptions
     *
     * .
     *
     */
    public function testBlacklistIdOptions()
    {

    }
    /**
     * Test case for blacklistIdPut
     *
     * .
     *
     */
    public function testBlacklistIdPut()
    {

    }
    /**
     * Test case for didsGet
     *
     * .
     *
     */
    public function testDidsGet()
    {

    }
    /**
     * Test case for didsIdOptions
     *
     * .
     *
     */
    public function testDidsIdOptions()
    {

    }
    /**
     * Test case for didsIdPatch
     *
     * .
     *
     */
    public function testDidsIdPatch()
    {

    }
    /**
     * Test case for didsOptions
     *
     * .
     *
     */
    public function testDidsOptions()
    {

    }
    /**
     * Test case for extensionsGet
     *
     * .
     *
     */
    public function testExtensionsGet()
    {

    }
    /**
     * Test case for extensionsIdOptions
     *
     * .
     *
     */
    public function testExtensionsIdOptions()
    {

    }
    /**
     * Test case for extensionsIdPatch
     *
     * .
     *
     */
    public function testExtensionsIdPatch()
    {

    }
    /**
     * Test case for extensionsOptions
     *
     * .
     *
     */
    public function testExtensionsOptions()
    {

    }
    /**
     * Test case for meGet
     *
     * .
     *
     */
    public function testMeGet()
    {

    }
    /**
     * Test case for meOptions
     *
     * .
     *
     */
    public function testMeOptions()
    {

    }
    /**
     * Test case for queuesGet
     *
     * .
     *
     */
    public function testQueuesGet()
    {

    }
    /**
     * Test case for queuesIdOptions
     *
     * .
     *
     */
    public function testQueuesIdOptions()
    {

    }
    /**
     * Test case for queuesIdPatch
     *
     * .
     *
     */
    public function testQueuesIdPatch()
    {

    }
    /**
     * Test case for queuesOptions
     *
     * .
     *
     */
    public function testQueuesOptions()
    {

    }
    /**
     * Test case for versionGet
     *
     * .
     *
     */
    public function testVersionGet()
    {

    }
    /**
     * Test case for versionOptions
     *
     * .
     *
     */
    public function testVersionOptions()
    {

    }
}
